export const countryOptions = [
    { label: "Tunis", value: "TUN" },
    { label: "Paris", value: "CDG" },
    { label: "London", value: "LHR" },
    { label: "New York", value: "JFK" },
    { label: "Berlin", value: "TXL" },
    { label: "Tokyo", value: "HND" },
    { label: "Rome", value: "FCO" },
    { label: "Madrid", value: "MAD" },
    { label: "Moscow", value: "SVO" },
    { label: "Dubai", value: "DXB" },
    { label: "Sydney", value: "SYD" },
    { label: "Cairo", value: "CAI" },
    { label: "Mumbai", value: "BOM" },
    { label: "Los Angeles", value: "LAX" },
    { label: "Singapore", value: "SIN" },
    { label: "Hong Kong", value: "HKG" },
    { label: "Istanbul", value: "IST" },
    { label: "Seoul", value: "ICN" },
    { label: "Beijing", value: "PEK" },
    { label: "Kuala Lumpur", value: "KUL" },
    { label: "Bangkok", value: "BKK" },
    { label: "Johannesburg", value: "JNB" },
    { label: "Cape Town", value: "CPT" },
    { label: "Buenos Aires", value: "EZE" },
    { label: "Rio de Janeiro", value: "GIG" },
    { label: "Mexico City", value: "MEX" },
    { label: "São Paulo", value: "GRU" },
    { label: "Lagos", value: "LOS" },
    { label: "Jakarta", value: "CGK" },
    { label: "Manila", value: "MNL" },
    { label: "Toronto", value: "YYZ" },
    { label: "Vancouver", value: "YVR" },
    { label: "Chicago", value: "ORD" },
    { label: "Montreal", value: "YUL" },
    { label: "Lisbon", value: "LIS" },
    { label: "Amsterdam", value: "AMS" },
    { label: "Zurich", value: "ZRH" },
    { label: "Geneva", value: "GVA" },
    { label: "Vienna", value: "VIE" },
    { label: "Stockholm", value: "ARN" },
    { label: "Helsinki", value: "HEL" },
    { label: "Oslo", value: "OSL" },
    { label: "Copenhagen", value: "CPH" },
    { label: "Athens", value: "ATH" },
    { label: "Reykjavik", value: "KEF" },
    { label: "Bucharest", value: "OTP" },
    { label: "Warsaw", value: "WAW" },
    { label: "Dublin", value: "DUB" },
    { label: "Santiago", value: "SCL" },
    { label: "Lima", value: "LIM" },
    { label: "Quito", value: "UIO" },
    { label: "Bogotá", value: "BOG" },
    { label: "Caracas", value: "CCS" },
    { label: "Lagos", value: "LOS" },
    { label: "Accra", value: "ACC" },
    { label: "Abuja", value: "ABV" },
    { label: "Dar es Salaam", value: "DAR" },
    { label: "Addis Ababa", value: "ADD" },
    { label: "Nairobi", value: "NBO" },
    { label: "Kigali", value: "KGL" },
    { label: "Mogadishu", value: "MGQ" },
  ];